apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazel-app
  labels:
    app: hazel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazel-app
  template:
    metadata:
      labels:
        app: hazel-app
    spec:
      containers:
        - name: hazel-app
          image: hz-app:0.0.1
          imagePullPolicy: Never
          env:
            - name: HAZELCAST_K8S_SERVICE_NAME
              value: hz-app-service
            - name: environment
              value: K8s
          ports:
            - containerPort: 8080
            - containerPort: 5701