apiVersion: v1
kind: Service
metadata:
  name: hz-app-service
spec:
  selector:
    app: hazel-app
  ports:
    - protocol: TCP
      port: 5701
      targetPort: 5701
      name: hazel-cast
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: app